services:
  - type: web
    name: medicalnoto
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false 