services:
  - type: web
    name: medinote-app
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medinote-db
          property: connectionString
      - key: ANTHROPIC_API_KEY
        sync: false
  - type: pserv
    name: medinote-db
    plan: starter
    databaseName: medinote
    user: medinote_user