services:
  - type: web
    name: medicalnoto
    runtime: node
    repo: https://github.com/kaixxz/MediNote
    branch: main
    buildCommand: |
      cd client && npm install && npm run build && cd ..
      npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PORT
        value: 5000